
name: CI/CD for Node.js Docker App

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Docker Image
        run: |
          IMAGE_NAME=my-nodejs-app
          TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$TAG .
          docker tag $IMAGE_NAME:$TAG ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$TAG

      - name: Push Docker Image to Docker Hub
        run: |
          IMAGE_NAME=my-nodejs-app
          TAG=${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$TAG

  